version: '3.8'

services:
  backend:
    image: rakuten-sku-backend:latest
    container_name: rakuten-sku-backend
    ports:
      - "8000:8000"
    volumes:
      - /var/rakuten_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - rakuten-network

  frontend:
    image: rakuten-sku-frontend:latest
    container_name: rakuten-sku-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rakuten-network

networks:
  rakuten-network:
    driver: bridge