services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rakuten-sku-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Tokyo
      - MAX_WORKERS=4
      - GUNICORN_TIMEOUT=300
    networks:
      - rakuten-sku-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 3G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rakuten-sku-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - rakuten-sku-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  rakuten-sku-network:
    driver: bridge

volumes:
  data:
    driver: local