version: '3.8'

services:
  backend:
    image: rakuten_sku_manager-backend:latest
    container_name: rakuten-sku-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./product_attributes_new.db:/app/product_attributes_new.db
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - rakuten-network

  frontend:
    image: rakuten_sku_manager-frontend:latest
    container_name: rakuten-sku-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rakuten-network

networks:
  rakuten-network:
    driver: bridge

volumes:
  data:
    driver: local