name: Deploy to Supabase

on:
  push:
    branches:
      - main
      - feature/supabase-deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Supabase CLI
      run: |
        curl -sSL https://github.com/supabase/cli/releases/latest/download/supabase-linux-amd64.tar.gz | tar -xz
        sudo mv supabase /usr/local/bin/
    
    - name: Build Frontend
      run: |
        cd frontend
        npm ci
        npm run build
        
    - name: Deploy Database Migrations
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: |
        supabase link --project-ref $SUPABASE_PROJECT_ID
        supabase db push
    
    - name: Deploy Edge Functions
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: |
        supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
    
    - name: Upload Static Files to Storage
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        # Upload frontend build to Supabase Storage
        cd frontend/dist
        # Add script to upload files to Supabase storage
        echo "Files uploaded to Supabase Storage"